----------------------------------------------------
-- Generic info
----------------------------------------------------

INSERT INTO UnitPromotions (Type, PediaType, IconAtlas, PortraitIndex, Sound) VALUES
('PROMOTION_FW_GUNBOAT',     	'PEDIA_NAVAL',    'CIV_COLOR_ATLAS_FW_PROMOTIONS', 42, 'AS2D_IF_LEVELUP'),
('PROMOTION_FW_SPACESHIP',     	'PEDIA_AIR',      'CIV_COLOR_ATLAS_FW_PROMOTIONS', 42, 'AS2D_IF_LEVELUP'),
('PROMOTION_FW_URANIUM',     	'PEDIA_AIR',      'PROMOTION_ATLAS_VP_01', 			4, 'AS2D_IF_LEVELUP'),
('PROMOTION_FW_EMANCIPATED',    'PEDIA_AIR',      'PROMOTION_ATLAS_VP_01', 		   25, 'AS2D_IF_LEVELUP'),
('PROMOTION_FW_ANGELNET',       'PEDIA_SHARED',   'CIV_COLOR_ATLAS_FW_PROMOTIONS', 16, 'AS2D_IF_LEVELUP'),
('PROMOTION_FW_APEXPREDATOR',   'PEDIA_MOUNTED',  'PROMOTION_ATLAS',               13, 'AS2D_IF_LEVELUP');

INSERT INTO UnitPromotions (Type, PediaType, IconAtlas, PortraitIndex, Sound, PromotionPrereqOr1, InterceptChanceChange) VALUES
('PROMOTION_FW_INTERCEPTION_V',   	'PEDIA_AIR',  	  'PROMOTION_ATLAS_VP_02', 7, 'AS2D_IF_LEVELUP', 'PROMOTION_INTERCEPTION_IV', 		15),
('PROMOTION_FW_INTERCEPTION_VI',   	'PEDIA_AIR',  	  'PROMOTION_ATLAS_VP_02', 7, 'AS2D_IF_LEVELUP', 'PROMOTION_FW_INTERCEPTION_V',  	15);

-- INSERT INTO UnitPromotions (Type, PediaType, IconAtlas, PortraitIndex, Sound, LostWithUpgrade, OrderPriority, CombatPercent) VALUES
-- ('PROMOTION_FW_IMPLANTS',       'PEDIA_SHARED',     'CIV_COLOR_ATLAS_FW_PROMOTIONS', 17, 'AS2D_IF_LEVELUP', 0, 1, 10);

INSERT INTO UnitPromotions 
(Type, 								Description,								Help,												PediaType,			 	PediaEntry,									IconAtlas, 				PortraitIndex, 	Sound, 				LostWithUpgrade,	CannotBeChosen, 	MovesChange,	IgnoreZOC,	VisibilityChange, 	LandAirDefenseBonus) VALUES
('PROMOTION_FW_ADVANCED_TACTICS',   'TXT_KEY_FW_PROMOTION_ADVANCED_TACTICS',	'TXT_KEY_FW_PROMOTION_ADVANCED_TACTICS_HELP',		'PEDIA_ATTRIBUTES',  	'TXT_KEY_FW_PROMOTION_ADVANCED_TACTICS',	'PROMOTION_ATLAS', 		23, 			'AS2D_IF_LEVELUP', 	0, 					1,					1,				1,			1,					20),
('PROMOTION_FW_IMPLANTS_WORKER',    'TXT_KEY_FW_PROMOTION_IMPLANTS_WORKER',		'TXT_KEY_FW_PROMOTION_IMPLANTS_WORKER_HELP',		'PEDIA_ATTRIBUTES',  	'TXT_KEY_FW_PROMOTION_IMPLANTS_WORKER',		'PROMOTION_ATLAS', 		36, 			'AS2D_IF_LEVELUP', 	0, 					1,					2,				0,			1,					20);

INSERT INTO UnitPromotions (Type, PediaType, IconAtlas, PortraitIndex, Sound, LostWithUpgrade, OrderPriority, CombatPercent) VALUES
('PROMOTION_FW_IMPLANTS_I',       'PEDIA_SHARED',     'CIV_COLOR_ATLAS_FW_PROMOTIONS', 17, 'AS2D_IF_LEVELUP', 0, 1, 8),
('PROMOTION_FW_IMPLANTS_II',       'PEDIA_SHARED',     'CIV_COLOR_ATLAS_FW_PROMOTIONS', 17, 'AS2D_IF_LEVELUP', 0, 1, 10),
('PROMOTION_FW_IMPLANTS_III',       'PEDIA_SHARED',     'CIV_COLOR_ATLAS_FW_PROMOTIONS', 17, 'AS2D_IF_LEVELUP', 0, 1, 12),
('PROMOTION_FW_IMPLANTS_IV',       'PEDIA_SHARED',     'CIV_COLOR_ATLAS_FW_PROMOTIONS', 17, 'AS2D_IF_LEVELUP', 0, 1, 15);

UPDATE UnitPromotions
SET Description = 'TXT_KEY_'||Type, Help = 'TXT_KEY_'||Type||'_HELP', PediaEntry = 'TXT_KEY_'||Type, CannotBeChosen = 1
WHERE Type IN (
'PROMOTION_FW_GUNBOAT',
'PROMOTION_FW_SPACESHIP',
'PROMOTION_FW_URANIUM',
'PROMOTION_FW_EMANCIPATED',
'PROMOTION_FW_INTERCEPTION_V',
'PROMOTION_FW_INTERCEPTION_VI',
'PROMOTION_FW_ANGELNET',
'PROMOTION_FW_APEXPREDATOR',
'PROMOTION_FW_IMPLANTS_I',
'PROMOTION_FW_IMPLANTS_II',
'PROMOTION_FW_IMPLANTS_III',
'PROMOTION_FW_IMPLANTS_IV');

INSERT INTO UnitPromotions (Type, Description, PediaEntry, Help, PediaType, IconAtlas, PortraitIndex, AdjacentMod, Sound) VALUES
	('PROMOTION_FW_MASTER_RACE', 'TXT_KEY_FW_PROMOTION_MASTER_RACE', 'TXT_KEY_FW_PROMOTION_MASTER_RACE', 'TXT_KEY_FW_PROMOTION_MASTER_RACE_HELP',	'PEDIA_SHARED',      'PROMOTION_ATLAS', 23, -15, 'AS2D_IF_LEVELUP');

----------------------------------------------------
-- Promotions' unique features
----------------------------------------------------
UPDATE UnitPromotions SET RangedDefenseMod = 15 WHERE Type = 'PROMOTION_FW_GUNBOAT';
UPDATE UnitPromotions SET CombatPercent = 30 WHERE Type = 'PROMOTION_FW_ANGELNET';
UPDATE UnitPromotions SET CombatPercent = 10 WHERE Type = 'PROMOTION_FW_SPACESHIP';
UPDATE UnitPromotions SET DefenseMod = 10 WHERE Type = 'PROMOTION_FW_URANIUM';
UPDATE UnitPromotions SET CombatPercent = 15, CanCrossMountains = 1, MovesChange = 1, IgnoreTerrainCost = 1, Amphib = 1, River = 1  WHERE Type = 'PROMOTION_FW_EMANCIPATED';
UPDATE UnitPromotions SET OpenAttack = 25, AttackWoundedMod = 10  WHERE Type = 'PROMOTION_FW_APEXPREDATOR';
UPDATE UnitPromotions SET CanCrossMountains = 1 WHERE Type = 'PROMOTION_ENGINEERING_CORP';

-- Stealth (bombers)
UPDATE UnitPromotions SET MaxHitPointsChange = 25, InterceptionDefenseDamageModifier = -12, EvasionChange = 12 WHERE Type = 'PROMOTION_STEALTH';
UPDATE Language_en_US SET Text = "+12% Chance to [COLOR_POSITIVE_TEXT]Evade Air Interception[ENDCOLOR].[NEWLINE]-12% Damage received when performing an [COLOR_POSITIVE_TEXT]Air Strike[ENDCOLOR].[NEWLINE]+25 Hit Points." WHERE Tag IN ('TXT_KEY_PROMOTION_STEALTH_HELP');

INSERT INTO UnitPromotions 
(Type, 									Description, 								Help, 											Sound, 				LostWithUpgrade, OrderPriority, CannotBeChosen,	PortraitIndex, 	IconAtlas,					PediaType, 			PediaEntry) VALUES
('PROMOTION_FW_DESTROY_BARBARIAN',		'TXT_KEY_PROMOTION_FW_DESTROY_BARBARIAN',	'TXT_KEY_PROMOTION_FW_DESTROY_BARBARIAN_HELP',	'AS2D_IF_LEVELUP',	0,				 0, 			1,				0, 				'JAR_TAINO_PROMO_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_FW_DESTROY_BARBARIAN');
UPDATE UnitPromotions SET BarbarianCombatBonus= 30 WHERE Type = 'PROMOTION_FW_DESTROY_BARBARIAN';

INSERT INTO Unit_FreePromotions 	
		(UnitType, 				PromotionType)
VALUES	('UNIT_FW_GUNBOAT', 	'PROMOTION_FW_DESTROY_BARBARIAN'),
		('UNIT_FW_ADV_GUNBOAT', 'PROMOTION_FW_DESTROY_BARBARIAN');

-- INSERT INTO UnitPromotions_Features
-- 	(PromotionType, 				FeatureType, 		IgnoreTerrainCostIn)
-- VALUES
-- 	('PROMOTION_FW_EMANCIPATED', 	'FEATURE_MARSH', 	1),
-- 	('PROMOTION_FW_EMANCIPATED', 	'FEATURE_FOREST', 	1),
-- 	('PROMOTION_FW_EMANCIPATED', 	'FEATURE_JUNGLE', 	1);

-- Free Promotions 
INSERT INTO Technology_FreePromotions
	(TechType, PromotionType)
VALUES
	('TECH_IMPLANTS', 			'PROMOTION_FW_IMPLANTS_WORKER'),
	('TECH_FUTURE_BALLISTICS', 	'PROMOTION_FW_ADVANCED_TACTICS'),
	('TECH_BIOMODIFICATION', 	'PROMOTION_FALLOUT_IMMUNITY');

UPDATE Technology_FreePromotions SET TechType = 'TECH_DYNAMITE' WHERE PromotionType = 'PROMOTION_ENGINEERING_CORP' AND TechType = 'TECH_BALLISTICS';

INSERT INTO UnitPromotions_CivilianUnitType
	(UnitType, PromotionType)
VALUES
	('UNIT_GREAT_GENERAL', 			'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_MONGOLIAN_KHAN', 		'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_ZULU_INDABA', 			'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_CARTHAGE_SHOPHET', 		'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_GREAT_ADMIRAL', 			'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_CARTHAGE_SHOPHET_BOAT', 	'PROMOTION_FW_ADVANCED_TACTICS'),
	('UNIT_ARCHAEOLOGIST', 			'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_FW_AUGMENTED_DIPLOMAT', 	'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_FW_MENTAT_DIPLOMAT', 	'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_FW_MODERN_COLONIST', 	'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_FW_SPACE_COLONIST', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_MUSICIAN', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_ARTIST', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_WRITER', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_ENGINEER', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_KHMER_TROMEAK', 			'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_SCIENTIST', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_GREAT_DIPLOMAT', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_IROQUOIS_TADODAHO', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_MERCHANT', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_VENETIAN_MERCHANT', 		'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_WORKER', 				'PROMOTION_FW_IMPLANTS_WORKER'),
	('UNIT_WORKBOAT', 				'PROMOTION_FW_IMPLANTS_WORKER');

----------------------------------------------
-- Summer Palace
----------------------------------------------
UPDATE UnitPromotions SET RivalTerritory = 0 WHERE Type = 'PROMOTION_NOBILITY';
UPDATE UnitPromotions SET RivalTerritory = 0 WHERE Type = 'PROMOTION_DIPLOMATIC_IMMUNITY';
UPDATE Language_en_US SET Text = 'Grants +15 [ICON_INFLUENCE] Influence when you conduct a Diplomatic Mission with a City-State.' WHERE Tag = 'TXT_KEY_PROMOTION_NOBILITY_HELP';
UPDATE Language_en_US SET Text = 'Grants +10 [ICON_INFLUENCE] Influence when you conduct a Diplomatic Mission with a City-State.' WHERE Tag = 'TXT_KEY_PROMOTION_DIPLOMATIC_IMMUNITY_HELP';


-- UPDATE UnitPromotions SET LostWithUpgrade = 1, HillsDoubleMove = 1 WHERE Type = 'PROMOTION_CBOEE_SKIRMISH';
-- INSERT INTO UnitPromotions_Features(PromotionType, FeatureType, DoubleMove) VALUES
-- ('PROMOTION_CBOEE_SKIRMISH', 'FEATURE_FOREST', 1),
-- ('PROMOTION_CBOEE_SKIRMISH', 'FEATURE_JUNGLE', 1);

INSERT INTO UnitPromotions 
			(Type, 										Description, 										Help, 														Sound, 				PlagueChance, 	PlaguePromotion, 							BarbarianCombatBonus,	MovesChange,	AttackMod,	DefenseMod, ExperiencePercent,	IgnoreZOC,	LostWithUpgrade,	CannotBeChosen, PortraitIndex, 	IconAtlas, 				PediaType, 			PediaEntry)
VALUES		('PROMOTION_NEUROTIC_POISON',               'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0',	            'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0_HELP', 	                'AS2D_IF_LEVELUP',	100, 			'PROMOTION_NEUROTIC_POISON_1', 	            0,						0,				0,			0,			0,					0,			0,					1, 				12, 			'promoMUC_atlas_01', 	'PEDIA_SCOUTING',	'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0');

INSERT INTO UnitPromotions 
			(Type, 										Description, 										Help, 													Sound, 				MaxHitPointsChange, EnemyHealChange, 	NeutralHealChange, 	FriendlyHealChange, PromotionDuration, 	PlagueID, 	PlaguePriority, BarbarianCombatBonus,	MovesChange,	AttackMod,	DefenseMod, ExperiencePercent,	IgnoreZOC,	LostWithUpgrade,	CannotBeChosen, PortraitIndex, 	IconAtlas, 				PediaType, 			PediaEntry)
VALUES		('PROMOTION_NEUROTIC_POISON_1',             'TXT_KEY_PROMOTION_FW_UNIT_SWARM_1',	            'TXT_KEY_PROMOTION_FW_UNIT_SWARM_1_HELP',               'AS2D_IF_LEVELUP',	-20, 				-15, 				-15, 				-15, 				3, 					1, 			0, 				0,						-1,				0,			0,			0,					0,			0,					1, 				13, 			'promoMUC_atlas_01', 	'PEDIA_SCOUTING',	'TXT_KEY_PROMOTION_FW_UNIT_SWARM_0');

----------------------------------------------------
-- Eligible combats
----------------------------------------------------

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType) VALUES
('PROMOTION_FW_EMANCIPATED',	   	'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_EMANCIPATED',	   	'UNITCOMBAT_RECON'),
('PROMOTION_FW_EMANCIPATED',	   	'UNITCOMBAT_GUN'),
('PROMOTION_FW_APEXPREDATOR',	   	'UNITCOMBAT_MOUNTED'),
('PROMOTION_SPLASH',			   	'UNITCOMBAT_GUN'),
('PROMOTION_FW_GENGINEERED',	   	'UNITCOMBAT_GUN'),
('PROMOTION_FW_GENGINEERED',	   	'UNITCOMBAT_MELEE'),
('PROMOTION_FW_GENGINEERED',	   	'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_GENGINEERED',	   	'UNITCOMBAT_RECON'),
('PROMOTION_FW_BIOMODS',           	'UNITCOMBAT_GUN'),
('PROMOTION_FW_BIOMODS',           	'UNITCOMBAT_MELEE'),
('PROMOTION_FW_BIOMODS',	       	'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_BIOMODS',	       	'UNITCOMBAT_RECON'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_MELEE'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_GUN'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_ARCHER'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_ARMOR'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_SIEGE'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_HELICOPTER'),
('PROMOTION_FW_MUTATION',	 		'UNITCOMBAT_RECON'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_FIGHTER'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_BOMBER'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_SUBMARINE'),
('PROMOTION_FW_MUTATION', 			'UNITCOMBAT_CARRIER'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_MELEE'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_GUN'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_MOUNTED'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_ARCHER'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_ARMOR'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_SIEGE'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_HELICOPTER'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_RECON'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_MASS_DIGESTION',		'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_MASS_DIGESTION', 		'UNITCOMBAT_SUBMARINE'),
('PROMOTION_MASS_DIGESTION',		'UNITCOMBAT_CARRIER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_MELEE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_GUN'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_MOUNTED'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_ARCHER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_ARMOR'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_SIEGE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_HELICOPTER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_RECON'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_FIGHTER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_BOMBER'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_SUBMARINE'),
('PROMOTION_MNEMOSYNE_EXPERIENCE', 'UNITCOMBAT_CARRIER'),
('PROMOTION_FW_ANGELNET',    	   'UNITCOMBAT_RECON'),
('PROMOTION_FW_ANGELNET',   	   'UNITCOMBAT_ARCHER'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_MOUNTED'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_MELEE'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_SIEGE'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_GUN'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_ARMOR'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_NAVALRANGED'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_NAVALMELEE'),
('PROMOTION_FW_ANGELNET',	       'UNITCOMBAT_HELICOPTER'),
('PROMOTION_FW_ANGELNET',   	   'UNITCOMBAT_SUBMARINE');

INSERT INTO UnitPromotions_UnitCombatMods (PromotionType, 						UnitCombatType, 						Modifier) 
VALUES	('PROMOTION_FW_MASTER_RACE',		                                	'UNITCOMBAT_GUN',				    		30);

INSERT INTO UnitPromotions_UnitClasses
	(PromotionType, UnitClassType, Attack, Defense)
VALUES
	('PROMOTION_ANTI_SUBMARINE_I', 'UNITCLASS_FW_MECHASUB', 33, 25),
	('PROMOTION_ANTI_SUBMARINE_I', 'UNITCLASS_FW_CYBERSUB', 33, 25),
	('PROMOTION_ANTI_SUBMARINE_II', 'UNITCLASS_FW_MECHASUB', 66, 50),
	('PROMOTION_ANTI_SUBMARINE_II', 'UNITCLASS_FW_CYBERSUB', 66, 50);


-- INSERT INTO Promotion_RankLists
-- VALUES
-- 	('PROMOTION_FW_INTERCEPTION_V', 	'INTERCEPTOR', 5),
-- 	('PROMOTION_FW_INTERCEPTION_VI', 	'INTERCEPTOR', 6);

------------------------------
-- UnitPromotions_YieldFromPillage
------------------------------
INSERT INTO UnitPromotions_YieldFromPillage
		(PromotionType, 					YieldType, 			Yield, 	YieldNoScale)
VALUES	('PROMOTION_MASS_DIGESTION', 		'YIELD_FOOD', 		0, 		100);
------------------------------
-- UnitPromotions_YieldFromKills
------------------------------
INSERT INTO UnitPromotions_YieldFromKills
			(PromotionType, 					YieldType,			Yield)
VALUES		('PROMOTION_MASS_DIGESTION',		'YIELD_FOOD',		200);

INSERT INTO UnitPromotions_UnitClasses
	(PromotionType, UnitClassType, Modifier)
VALUES
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_APACHE',       150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_VERTOL',       150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_HOVERTANK',    150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_NEXUS',        150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_HELICARIIER',  150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_NANOHIVE',     150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_MEGAHIVE',     150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_MODERN_DRONE', 150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_HYBRID_DRONE', 150),
	('PROMOTION_ANTI_HELICOPTER', 'UNITCLASS_FW_BIODRONE',     150);


----------------------------------------------------
-- Text (en_US)
----------------------------------------------------

INSERT INTO Language_en_US (Tag, Text) VALUES
-- Implants
('TXT_KEY_PROMOTION_FW_IMPLANTS_I', 'Implants I'),
('TXT_KEY_PROMOTION_FW_IMPLANTS_I_HELP', '+8% [ICON_STRENGTH] CS'),
('TXT_KEY_PROMOTION_FW_IMPLANTS_II', 'Implants II'),
('TXT_KEY_PROMOTION_FW_IMPLANTS_II_HELP', '+10% [ICON_STRENGTH] CS'),
('TXT_KEY_PROMOTION_FW_IMPLANTS_III', 'Implants III'),
('TXT_KEY_PROMOTION_FW_IMPLANTS_III_HELP', '+12% [ICON_STRENGTH] CS'),
('TXT_KEY_PROMOTION_FW_IMPLANTS_IV', 'Implants IV'),
('TXT_KEY_PROMOTION_FW_IMPLANTS_IV_HELP', '+15% [ICON_STRENGTH] CS');